name = "spin"
uuid = "733b5546-3ae9-11ef-2523-8101814058f1"
authors = ["Ibtissam Mimoun<ibtissam.mimoun@enseeiht.fr>", "Jean-Baptiste Caillau <jean-baptiste.caillau@univ-cotedazur.fr>"]
version = "0.1.0"

[deps]
HSL = "34c5aeac-e683-54a6-a0e9-6e0fdc586c50"
HSL_jll = "017b0a0e-03f4-516a-9b91-836bbd1904dd"
MINPACK = "4854310b-de5a-5eb6-a2a5-c1dee2bd17f9"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
OptimalControl = "5f98b655-cc9a-415a-b60e-744165666948"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
